/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package su.svn;

public class Main {

    public static void main(String[] args) throws Exception {
        Application.Instance.start();
    }
}
