/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package su.svn;

import org.apache.catalina.LifecycleException;
import org.junit.Before;
import org.junit.Test;
import su.svn.executors.FactorizerExecutor;
import su.svn.tomcat.Embedded;

import java.lang.reflect.Constructor;
import java.lang.reflect.Field;

public class MainTest {

    public static void clearEmbedded() throws Exception {
        Class<Embedded> clazz = Embedded.class;

        Constructor<Embedded> constructor = clazz.getDeclaredConstructor();
        constructor.setAccessible(true);
        Embedded mock = constructor.newInstance();

        Field consoleOutputField = clazz.getDeclaredField("embedded");
        consoleOutputField.setAccessible(true);
        consoleOutputField.set(mock, null);
    }

    @Before
    public void setUp() throws Exception {
        clearEmbedded();
    }

    @Test
    public void main() throws Exception {
        final int sleepBeforeStop = FactorizerExecutor.SLEEP_BEFORE_GET
                + FactorizerExecutor.START_POINT * FactorizerExecutor.MAX_SIZE;
        new Thread(() -> {
            try {
                int count = 0;
                while ( ! FactorizerExecutor.get().isFinished() && count < sleepBeforeStop) {
                    //noinspection BusyWait
                    Thread.sleep(1);
                    count++;
                }
                System.err.println("is finished: " + FactorizerExecutor.get().isFinished());
                Embedded.get().stop();
            } catch (InterruptedException | LifecycleException e) {
                e.printStackTrace();
            }
        }).start();
        Main.main(new String[]{});
    }
}
